ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Creación de usuario
CREATE USER walterw IDENTIFIED BY 1234
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;
SET SERVEROUTPUT ON;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE TO walterw;

-- ==========================================================
-- 1. LIMPIEZA
-- ==========================================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name NOT LIKE 'ISEQ$$%') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- ==========================================================
-- 2. CREACIÓN DE TABLAS
-- ==========================================================

-- 2.1. Usuarios (Tabla Padre)
CREATE TABLE Usuarios (
    dni               VARCHAR2(15) NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    apellido_paterno  VARCHAR2(100) NOT NULL,
    apellido_materno  VARCHAR2(100),
    CONSTRAINT pk_usuarios PRIMARY KEY (dni)
);

-- 2.2. Clientes y Empleados (Herencia)
CREATE TABLE Clientes (
    dni VARCHAR2(15) NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (dni),
    CONSTRAINT fk_clientes_usuarios FOREIGN KEY (dni) REFERENCES Usuarios(dni) ON DELETE CASCADE
);

CREATE TABLE Empleados (
    dni               VARCHAR2(15) NOT NULL,
    puesto            VARCHAR2(50) NOT NULL,
    fecha_contratacion DATE DEFAULT SYSDATE,
    usuario_sistema   VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT pk_empleados PRIMARY KEY (dni),
    CONSTRAINT fk_empleados_usuarios FOREIGN KEY (dni) REFERENCES Usuarios(dni) ON DELETE CASCADE
);

-- 2.3. Inventario
CREATE TABLE Proveedores (
    id_proveedor      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    contacto_telefono VARCHAR2(15),
    email             VARCHAR2(100),
    direccion         VARCHAR2(255),
    estado            VARCHAR2(10) DEFAULT 'Activo' NOT NULL,
    CONSTRAINT pk_proveedores PRIMARY KEY (id_proveedor)
);

CREATE TABLE Categorias (
    id_categoria      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    descripcion       VARCHAR2(255),
    CONSTRAINT pk_categorias PRIMARY KEY (id_categoria)
);

CREATE TABLE Medicamentos (
    id_medicamento    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    id_categoria      NUMBER(10) NOT NULL,
    id_proveedor      NUMBER(10),
    stock             NUMBER(6) DEFAULT 0 NOT NULL,
    precio_compra     NUMBER(10, 2) NOT NULL,
    precio_venta      NUMBER(10, 2) NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    lote              VARCHAR2(50) NOT NULL,
    ubicacion         VARCHAR2(50), -- Es opcional (NULL permitido)
    descripcion       VARCHAR2(500), -- Es opcional (NULL permitido)
    estado            VARCHAR2(10) DEFAULT 'Activo' NOT NULL,
    CONSTRAINT pk_medicamentos PRIMARY KEY (id_medicamento),
    CONSTRAINT fk_medicamentos_cat FOREIGN KEY (id_categoria) REFERENCES Categorias(id_categoria),
    CONSTRAINT fk_medicamentos_prov FOREIGN KEY (id_proveedor) REFERENCES Proveedores(id_proveedor),
    CONSTRAINT chk_medicamentos_stock CHECK (stock >= 0)
);

-- 2.4. Ventas y Auditoría
CREATE TABLE Ventas (
    id_venta          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dni_cliente       VARCHAR2(15) NOT NULL,
    dni_empleado      VARCHAR2(15) NOT NULL,
    fecha_venta       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    total_venta       NUMBER(10, 2) DEFAULT 0,
    CONSTRAINT pk_ventas PRIMARY KEY (id_venta),
    CONSTRAINT fk_ventas_cli FOREIGN KEY (dni_cliente) REFERENCES Clientes(dni),
    CONSTRAINT fk_ventas_emp FOREIGN KEY (dni_empleado) REFERENCES Empleados(dni)
);

CREATE TABLE Venta_Detalle (
    id_detalle        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_venta          NUMBER(10) NOT NULL,
    id_medicamento    NUMBER(10) NOT NULL,
    cantidad          NUMBER(4) NOT NULL,
    precio_unitario_venta NUMBER(10, 2) NOT NULL,
    subtotal AS (cantidad * precio_unitario_venta),
    CONSTRAINT pk_venta_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_detalle_vta FOREIGN KEY (id_venta) REFERENCES Ventas(id_venta) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_med FOREIGN KEY (id_medicamento) REFERENCES Medicamentos(id_medicamento)
);

CREATE TABLE Auditoria_Medicamentos (
    id_auditoria      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_medicamento_afectado NUMBER(10),
    nombre_medicamento  VARCHAR2(100),
    accion_realizada    VARCHAR2(20),
    usuario_db          VARCHAR2(50),
    fecha_accion        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_auditoria PRIMARY KEY (id_auditoria)
);

-- ==========================================================
-- 3. TRIGGERS
-- ==========================================================
CREATE OR REPLACE TRIGGER trg_reducir_stock_venta
AFTER INSERT ON Venta_Detalle FOR EACH ROW
BEGIN
    UPDATE Medicamentos
    SET stock = stock - :NEW.cantidad,
        estado = CASE WHEN (stock - :NEW.cantidad) <= 0 THEN 'Agotado' ELSE estado END
    WHERE id_medicamento = :NEW.id_medicamento;
    IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Medicamento no encontrado ID: ' || :NEW.id_medicamento); END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_validar_vencimiento
BEFORE INSERT OR UPDATE ON Medicamentos FOR EACH ROW
BEGIN
    IF :NEW.fecha_vencimiento < TRUNC(SYSDATE) THEN RAISE_APPLICATION_ERROR(-20001, 'No se puede registrar medicamento vencido.'); END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_auditar_medicamento_accion
AFTER INSERT OR UPDATE OR DELETE ON Medicamentos FOR EACH ROW
BEGIN
    IF UPDATING('estado') AND :NEW.estado = 'Inactivo' AND :OLD.estado != 'Inactivo' THEN
        INSERT INTO Auditoria_Medicamentos (
            id_medicamento_afectado, 
            nombre_medicamento, 
            accion_realizada, 
            usuario_db, 
            fecha_accion
        ) VALUES (
            :OLD.id_medicamento, 
            :OLD.nombre, 
            'ELIMINACION_LOGICA',
            USER, 
            SYSTIMESTAMP
        );

    ELSIF DELETING THEN
        INSERT INTO Auditoria_Medicamentos (
            id_medicamento_afectado, 
            nombre_medicamento, 
            accion_realizada, 
            usuario_db, 
            fecha_accion
        ) VALUES (
            :OLD.id_medicamento, 
            :OLD.nombre, 
            'ELIMINACION_FISICA', 
            USER, 
            SYSTIMESTAMP
        );
    END IF;
END;
/

-- ==========================================================
-- 4. DATOS INICIALES
-- ==========================================================
-- Categorías y Proveedores
INSERT INTO Categorias (nombre, descripcion) VALUES ('Analgesicos', 'Alivio dolor');
INSERT INTO Categorias (nombre, descripcion) VALUES ('Antibioticos', 'Infecciones');
INSERT INTO Categorias (nombre, descripcion) VALUES ('Vitaminas', 'Suplementos');
INSERT INTO Proveedores (nombre, contacto_telefono, email, direccion) VALUES ('PharmaCorp', '987654321', 'ventas@pharma.com', 'Av Principal');
INSERT INTO Proveedores (nombre, contacto_telefono, email, direccion) VALUES ('Medilab', '999888777', 'pedidos@medilab.com', 'Jr Secundario');

-- Usuarios (Clientes y Empleados)
INSERT INTO Usuarios (dni, nombre, apellido_paterno, apellido_materno) VALUES ('12345678', 'Walter', 'White', 'Hartwell');
INSERT INTO Usuarios (dni, nombre, apellido_paterno, apellido_materno) VALUES ('87654322', 'Jesse', 'Pinkman', NULL);
INSERT INTO Usuarios (dni, nombre, apellido_paterno, apellido_materno) VALUES ('45678901', 'Ana', 'Gomez', NULL);
INSERT INTO Usuarios (dni, nombre, apellido_paterno, apellido_materno) VALUES ('87654321', 'Luis', 'Torres', NULL);

-- Roles
INSERT INTO Empleados (dni, puesto, usuario_sistema) VALUES ('12345678', 'Quimico', 'walterw');
INSERT INTO Empleados (dni, puesto, usuario_sistema) VALUES ('87654322', 'Tecnico', 'jpinkman');
INSERT INTO Clientes (dni) VALUES ('45678901');
INSERT INTO Clientes (dni) VALUES ('87654321');

-- Medicamentos
INSERT INTO Medicamentos (nombre, id_categoria, id_proveedor, stock, precio_compra, precio_venta, fecha_vencimiento, lote, ubicacion, estado)
VALUES ('Paracetamol 500mg', 1, 1, 100, 0.50, 1.00, TO_DATE('2026-12-31', 'YYYY-MM-DD'), 'LOTE-P001', 'A-01', 'Activo');
INSERT INTO Medicamentos (nombre, id_categoria, id_proveedor, stock, precio_compra, precio_venta, fecha_vencimiento, lote, ubicacion, estado)
VALUES ('Amoxicilina 250mg', 2, 2, 50, 1.20, 2.50, TO_DATE('2026-10-31', 'YYYY-MM-DD'), 'LOTE-A002', 'B-03', 'Activo');
INSERT INTO Medicamentos (nombre, id_categoria, id_proveedor, stock, precio_compra, precio_venta, fecha_vencimiento, lote, ubicacion, estado)
VALUES ('Vitamina C 1000mg', 3, 1, 200, 0.80, 1.50, TO_DATE('2027-06-30', 'YYYY-MM-DD'), 'LOTE-V003', 'C-05', 'Activo');

-- Ventas Históricas
INSERT INTO Ventas (dni_cliente, dni_empleado, fecha_venta, total_venta) VALUES ('45678901', '12345678', SYSTIMESTAMP, 3.50);
INSERT INTO Venta_Detalle (id_venta, id_medicamento, cantidad, precio_unitario_venta) VALUES (1, 2, 2, 2.50);
INSERT INTO Venta_Detalle (id_venta, id_medicamento, cantidad, precio_unitario_venta) VALUES (1, 3, 1, 1.50); -- Ajuste de precio unitario para cuadrar

INSERT INTO Ventas (dni_cliente, dni_empleado, fecha_venta, total_venta) VALUES ('87654321', '87654322', SYSTIMESTAMP, 25.00);
INSERT INTO Venta_Detalle (id_venta, id_medicamento, cantidad, precio_unitario_venta) VALUES (2, 2, 10, 2.50);

COMMIT;

-- ==========================================================
-- 5. PAQUETE DE GESTIÓN
-- ==========================================================
CREATE OR REPLACE PACKAGE pkg_gestion_farmacia AS
    PROCEDURE p_registrar_medicamento (
        p_nombre IN VARCHAR2, p_id_categoria IN NUMBER, p_id_proveedor IN NUMBER,
        p_stock IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
        p_fecha_vencimiento IN VARCHAR2, p_lote IN VARCHAR2,
        p_ubicacion IN VARCHAR2 DEFAULT NULL, p_descripcion IN VARCHAR2 DEFAULT NULL
    );

    PROCEDURE p_editar_medicamento_completo (
        p_id_medicamento IN NUMBER, p_nombre IN VARCHAR2, p_id_categoria IN NUMBER, p_id_proveedor IN NUMBER,
        p_stock IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
        p_fecha_vencimiento IN VARCHAR2, p_lote IN VARCHAR2, p_ubicacion IN VARCHAR2 DEFAULT NULL, p_descripcion IN VARCHAR2 DEFAULT NULL
    );

    PROCEDURE p_editar_precio (p_id_medicamento IN NUMBER, p_nuevo_precio_compra IN NUMBER, p_nuevo_precio_venta IN NUMBER);
    PROCEDURE p_actualizar_stock (p_id_medicamento IN NUMBER, p_cantidad_agregada IN NUMBER);
    
    -- Este procedimiento disparará la 'ELIMINACION_LOGICA' en el trigger
    PROCEDURE p_eliminar_medicamento (p_id_medicamento IN NUMBER);

    PROCEDURE p_registrar_venta_con_cliente (
        p_dni_cliente IN VARCHAR2, p_nombre_cli IN VARCHAR2, p_ape_pat_cli IN VARCHAR2, p_ape_mat_cli IN VARCHAR2,
        p_dni_empleado IN VARCHAR2, p_total_venta IN NUMBER, p_id_venta_generada OUT NUMBER
    );
END pkg_gestion_farmacia;
/

CREATE OR REPLACE PACKAGE BODY pkg_gestion_farmacia AS
    PROCEDURE p_registrar_medicamento (
        p_nombre IN VARCHAR2, p_id_categoria IN NUMBER, p_id_proveedor IN NUMBER,
        p_stock IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
        p_fecha_vencimiento IN VARCHAR2, p_lote IN VARCHAR2, p_ubicacion IN VARCHAR2, p_descripcion IN VARCHAR2
    ) AS BEGIN
        INSERT INTO Medicamentos (nombre, id_categoria, id_proveedor, stock, precio_compra, precio_venta, fecha_vencimiento, lote, ubicacion, descripcion)
        VALUES (p_nombre, p_id_categoria, p_id_proveedor, p_stock, p_precio_compra, p_precio_venta, TO_DATE(p_fecha_vencimiento,'YYYY-MM-DD'), p_lote, p_ubicacion, p_descripcion);
        COMMIT;
    END;

    PROCEDURE p_editar_medicamento_completo (
        p_id_medicamento IN NUMBER, p_nombre IN VARCHAR2, p_id_categoria IN NUMBER, p_id_proveedor IN NUMBER,
        p_stock IN NUMBER, p_precio_compra IN NUMBER, p_precio_venta IN NUMBER,
        p_fecha_vencimiento IN VARCHAR2, p_lote IN VARCHAR2, p_ubicacion IN VARCHAR2, p_descripcion IN VARCHAR2
    ) AS BEGIN
        UPDATE Medicamentos SET nombre = p_nombre, id_categoria = p_id_categoria, id_proveedor = p_id_proveedor,
            stock = p_stock, precio_compra = p_precio_compra, precio_venta = p_precio_venta,
            fecha_vencimiento = TO_DATE(p_fecha_vencimiento, 'YYYY-MM-DD'), lote = p_lote, ubicacion = p_ubicacion, descripcion = p_descripcion
        WHERE id_medicamento = p_id_medicamento;
        COMMIT;
    END;

    PROCEDURE p_editar_precio (p_id_medicamento IN NUMBER, p_nuevo_precio_compra IN NUMBER, p_nuevo_precio_venta IN NUMBER) AS BEGIN
        UPDATE Medicamentos SET precio_compra = p_nuevo_precio_compra, precio_venta = p_nuevo_precio_venta WHERE id_medicamento = p_id_medicamento;
        COMMIT;
    END;

    PROCEDURE p_actualizar_stock (p_id_medicamento IN NUMBER, p_cantidad_agregada IN NUMBER) AS BEGIN
        UPDATE Medicamentos SET stock = stock + p_cantidad_agregada, estado = CASE WHEN estado='Agotado' THEN 'Activo' ELSE estado END WHERE id_medicamento = p_id_medicamento;
        COMMIT;
    END;

    PROCEDURE p_eliminar_medicamento (p_id_medicamento IN NUMBER) AS BEGIN
        UPDATE Medicamentos SET estado = 'Inactivo' WHERE id_medicamento = p_id_medicamento;
        COMMIT;
    END;

    PROCEDURE p_registrar_venta_con_cliente (
        p_dni_cliente IN VARCHAR2, p_nombre_cli IN VARCHAR2, p_ape_pat_cli IN VARCHAR2, p_ape_mat_cli IN VARCHAR2,
        p_dni_empleado IN VARCHAR2, p_total_venta IN NUMBER, p_id_venta_generada OUT NUMBER
    ) AS BEGIN
        MERGE INTO Usuarios u USING (SELECT p_dni_cliente AS dni FROM dual) s ON (u.dni = s.dni)
        WHEN MATCHED THEN UPDATE SET nombre = p_nombre_cli, apellido_paterno = p_ape_pat_cli, apellido_materno = p_ape_mat_cli
        WHEN NOT MATCHED THEN INSERT (dni, nombre, apellido_paterno, apellido_materno) VALUES (p_dni_cliente, p_nombre_cli, p_ape_pat_cli, p_ape_mat_cli);

        INSERT INTO Clientes (dni) SELECT p_dni_cliente FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM Clientes WHERE dni = p_dni_cliente);
        INSERT INTO Ventas (dni_cliente, dni_empleado, total_venta) VALUES (p_dni_cliente, p_dni_empleado, p_total_venta) RETURNING id_venta INTO p_id_venta_generada;
    END;
END pkg_gestion_farmacia;
/

-- ==========================================================
-- 6. PAQUETE REPORTES
-- ==========================================================
CREATE OR REPLACE PACKAGE pkg_reportes_farmacia AS
    TYPE T_CURSOR IS REF CURSOR;

    -- 1. Inventario General
    PROCEDURE p_reporte_medicamentos_por_categoria (p_cursor OUT T_CURSOR);
    
    -- 2. Rentabilidad
    PROCEDURE p_reporte_rentabilidad_productos (p_cursor OUT T_CURSOR);
    
    -- 3. Auditoría
    PROCEDURE p_reporte_auditoria_cambios (p_cursor OUT T_CURSOR);
    
    -- 4. Inactivos
    PROCEDURE p_reporte_medicamentos_inactivos (p_cursor OUT T_CURSOR);
    
    -- 5. Vencimientos
    PROCEDURE p_reporte_medicamentos_proximos_vencer (p_dias IN NUMBER, p_cursor OUT T_CURSOR);
    
    -- 6. Stock Crítico
    PROCEDURE p_reporte_medicamentos_sin_stock (p_cursor OUT T_CURSOR);
    
    -- 7. Ventas por Empleado
    PROCEDURE p_reporte_ventas_por_empleado (p_cursor OUT T_CURSOR);
    
    -- 8. Ventas por Cliente
    PROCEDURE p_reporte_ventas_por_cliente (p_cursor OUT T_CURSOR);
    
    -- 9. Top Vendidos
    PROCEDURE p_reporte_top_5_vendidos (p_cursor OUT T_CURSOR);
    
    -- 10. Ingresos Mensuales
    PROCEDURE p_reporte_ingresos_por_mes (p_cursor OUT T_CURSOR);

END pkg_reportes_farmacia;
/

CREATE OR REPLACE PACKAGE BODY pkg_reportes_farmacia AS

    -- 1. INVENTARIO GENERAL
    PROCEDURE p_reporte_medicamentos_por_categoria (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT c.nombre as categoria, m.nombre as medicamento, m.stock, m.precio_venta 
            FROM Medicamentos m JOIN Categorias c ON m.id_categoria = c.id_categoria 
            WHERE m.estado = 'Activo' ORDER BY c.nombre, m.nombre;
    END;

    -- 2. RENTABILIDAD (NUEVO)
    PROCEDURE p_reporte_rentabilidad_productos (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT nombre, precio_compra, precio_venta, 
                   (precio_venta - precio_compra) AS ganancia_unitaria,
                   ROUND(((precio_venta - precio_compra) / NULLIF(precio_venta,0)) * 100, 1) AS margen_porcentaje
            FROM Medicamentos WHERE estado = 'Activo' ORDER BY ganancia_unitaria DESC;
    END;

    -- 3. AUDITORÍA (NUEVO)
    PROCEDURE p_reporte_auditoria_cambios (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT fecha_accion, usuario_db, accion_realizada, nombre_medicamento
            FROM Auditoria_Medicamentos ORDER BY fecha_accion DESC;
    END;

    -- 4. INACTIVOS (NUEVO)
    PROCEDURE p_reporte_medicamentos_inactivos (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT m.nombre, m.lote, m.ubicacion, m.stock
            FROM Medicamentos m WHERE m.estado = 'Inactivo' ORDER BY m.nombre;
    END;

    -- 5. VENCIMIENTOS (Próximos días)
    PROCEDURE p_reporte_medicamentos_proximos_vencer (p_dias IN NUMBER, p_cursor OUT T_CURSOR) AS BEGIN 
        OPEN p_cursor FOR 
            SELECT nombre, lote, fecha_vencimiento, (fecha_vencimiento - TRUNC(SYSDATE)) as dias_restantes
            FROM Medicamentos 
            WHERE fecha_vencimiento BETWEEN TRUNC(SYSDATE) AND (TRUNC(SYSDATE) + p_dias) AND estado = 'Activo'
            ORDER BY fecha_vencimiento ASC; 
    END;

    -- 6. SIN STOCK
    PROCEDURE p_reporte_medicamentos_sin_stock (p_cursor OUT T_CURSOR) AS BEGIN 
        OPEN p_cursor FOR 
            SELECT nombre, lote, estado, id_proveedor
            FROM Medicamentos WHERE stock <= 0 OR estado = 'Agotado'; 
    END;

    -- 7. VENTAS POR EMPLEADO
    PROCEDURE p_reporte_ventas_por_empleado (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT u.nombre || ' ' || u.apellido_paterno as empleado, COUNT(v.id_venta) as total_ventas, SUM(v.total_venta) as total_dinero
            FROM Ventas v JOIN Empleados e ON v.dni_empleado = e.dni JOIN Usuarios u ON e.dni = u.dni 
            GROUP BY u.nombre, u.apellido_paterno ORDER BY total_dinero DESC;
    END;

    -- 8. VENTAS POR CLIENTE
    PROCEDURE p_reporte_ventas_por_cliente (p_cursor OUT T_CURSOR) AS BEGIN
        OPEN p_cursor FOR 
            SELECT u.nombre || ' ' || u.apellido_paterno as cliente, COUNT(v.id_venta) as compras, SUM(v.total_venta) as gastado
            FROM Ventas v JOIN Clientes c ON v.dni_cliente = c.dni JOIN Usuarios u ON c.dni = u.dni 
            GROUP BY u.nombre, u.apellido_paterno ORDER BY gastado DESC;
    END;

    -- 9. TOP 5 VENDIDOS
    PROCEDURE p_reporte_top_5_vendidos (p_cursor OUT T_CURSOR) AS BEGIN 
        OPEN p_cursor FOR 
            SELECT m.nombre, SUM(d.cantidad) as total_unidades
            FROM Venta_Detalle d JOIN Medicamentos m ON d.id_medicamento = m.id_medicamento 
            GROUP BY m.nombre ORDER BY total_unidades DESC FETCH FIRST 5 ROWS ONLY; 
    END;

    -- 10. INGRESOS MENSUALES
    PROCEDURE p_reporte_ingresos_por_mes (p_cursor OUT T_CURSOR) AS BEGIN 
        OPEN p_cursor FOR 
            SELECT TO_CHAR(fecha_venta, 'YYYY-MM') as mes, COUNT(id_venta) as num_ventas, SUM(total_venta) as total_ingresos
            FROM Ventas GROUP BY TO_CHAR(fecha_venta, 'YYYY-MM') ORDER BY mes DESC; 
    END;

END pkg_reportes_farmacia;
/


-- ==========================================================
-- 1. REPORTE: LISTA DE MEDICAMENTOS POR CATEGORÍA
-- ==========================================================
DECLARE
    CURSOR c_meds IS
        SELECT c.nombre AS categoria, m.nombre AS medicamento, m.stock, m.precio_venta
        FROM Medicamentos m
        JOIN Categorias c ON m.id_categoria = c.id_categoria
        WHERE m.estado = 'Activo'
        ORDER BY c.nombre, m.nombre;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 1. INVENTARIO POR CATEGORIA ===');
    FOR r IN c_meds LOOP
        DBMS_OUTPUT.PUT_LINE('[' || r.categoria || '] ' || r.medicamento || 
                             ' | Stock: ' || r.stock || 
                             ' | Precio: S/.' || r.precio_venta);
    END LOOP;
END;
/

-- ==========================================================
-- 2. REPORTE: RENTABILIDAD POR PRODUCTO
-- ==========================================================
DECLARE
    CURSOR c_rentabilidad IS
        SELECT nombre, precio_compra, precio_venta, 
               (precio_venta - precio_compra) AS ganancia_unitaria,
               ROUND(((precio_venta - precio_compra) / NULLIF(precio_venta,0)) * 100, 1) AS margen_pct
        FROM Medicamentos 
        WHERE estado = 'Activo'
        ORDER BY ganancia_unitaria DESC;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 2. ANALISIS DE RENTABILIDAD (Ganancia por unidad) ===');
    FOR r IN c_rentabilidad LOOP
        DBMS_OUTPUT.PUT_LINE(r.nombre || 
                             ' | Compra: S/.' || r.precio_compra || 
                             ' | Venta: S/.' || r.precio_venta ||
                             ' | GANA: S/.' || r.ganancia_unitaria || ' (' || r.margen_pct || '%)');
    END LOOP;
END;
/

-- ==========================================================
-- 3. REPORTE: AUDITORÍA DE CAMBIOS
-- ==========================================================
DECLARE
    CURSOR c_audit IS
        SELECT TO_CHAR(fecha_accion, 'DD/MM HH24:MI') as fecha, 
               usuario_db, accion_realizada, nombre_medicamento
        FROM Auditoria_Medicamentos
        ORDER BY fecha_accion DESC
        FETCH FIRST 20 ROWS ONLY;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 3. AUDITORIA DE SEGURIDAD (Últimos movimientos) ===');
    FOR r IN c_audit LOOP
        DBMS_OUTPUT.PUT_LINE(r.fecha || ' | Usuario: ' || r.usuario_db || 
                             ' | Acción: ' || r.accion_realizada || 
                             ' | Item: ' || r.nombre_medicamento);
    END LOOP;
END;
/

-- ==========================================================
-- 4. REPORTE: MEDICAMENTOS INACTIVOS
-- ==========================================================
DECLARE
    CURSOR c_inactivos IS
        SELECT nombre, lote, ubicacion, stock
        FROM Medicamentos
        WHERE estado = 'Inactivo'
        ORDER BY nombre;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 4. MEDICAMENTOS INACTIVOS (Para retirar de estantería) ===');
    FOR r IN c_inactivos LOOP
        DBMS_OUTPUT.PUT_LINE('Medicamento: ' || r.nombre || 
                             ' | Ubicación: ' || NVL(r.ubicacion, 'Sin Asignar') || 
                             ' | Stock remanente: ' || r.stock);
    END LOOP;
END;
/

-- ==========================================================
-- 5. REPORTE: MEDICAMENTOS PRÓXIMOS A VENCER
-- ==========================================================
DECLARE
    CURSOR c_vencer IS
        SELECT nombre, fecha_vencimiento, lote, (fecha_vencimiento - TRUNC(SYSDATE)) as dias
        FROM Medicamentos
        WHERE fecha_vencimiento BETWEEN SYSDATE AND SYSDATE + 60 -- Ampliado a 60 días
          AND estado = 'Activo'
        ORDER BY fecha_vencimiento;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 5. ALERTA DE VENCIMIENTO (Próximos 60 días) ===');
    FOR r IN c_vencer LOOP
        DBMS_OUTPUT.PUT_LINE('ALERTA: ' || r.nombre || 
                             ' | Lote: ' || r.lote || 
                             ' | Vence en: ' || r.dias || ' días (' || TO_CHAR(r.fecha_vencimiento, 'DD/MM/YYYY') || ')');
    END LOOP;
END;
/

-- ==========================================================
-- 6. REPORTE: MEDICAMENTOS SIN STOCK
-- ==========================================================
DECLARE
    CURSOR c_sin_stock IS
        SELECT nombre, id_proveedor
        FROM Medicamentos
        WHERE stock <= 0 OR estado = 'Agotado';
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 6. MEDICAMENTOS AGOTADOS (Reponer) ===');
    FOR r IN c_sin_stock LOOP
        DBMS_OUTPUT.PUT_LINE('Falta: ' || r.nombre || ' (Contactar Proveedor ID: ' || r.id_proveedor || ')');
    END LOOP;
END;
/

-- ==========================================================
-- 7. REPORTE: VENTAS POR EMPLEADO (Rendimiento)
-- ==========================================================
DECLARE
    CURSOR c_ventas_emp IS
        SELECT u.nombre || ' ' || u.apellido_paterno AS empleado,
               COUNT(v.id_venta) AS total_ventas,
               SUM(v.total_venta) AS total_monto
        FROM Ventas v
        JOIN Empleados e ON v.dni_empleado = e.dni
        JOIN Usuarios u ON e.dni = u.dni
        GROUP BY u.nombre, u.apellido_paterno
        ORDER BY total_monto DESC;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 7. RANKING DE VENDEDORES ===');
    FOR r IN c_ventas_emp LOOP
        DBMS_OUTPUT.PUT_LINE(r.empleado || 
                             ' | Tickets: ' || r.total_ventas || 
                             ' | Recaudado: S/.' || NVL(r.total_monto, 0));
    END LOOP;
END;
/

-- ==========================================================
-- 8. REPORTE: VENTAS POR CLIENTE (Fidelización)
-- ==========================================================
DECLARE
    CURSOR c_ventas_cli IS
        SELECT u.nombre || ' ' || u.apellido_paterno AS cliente,
               COUNT(v.id_venta) AS total_compras,
               SUM(v.total_venta) AS gastado
        FROM Ventas v
        JOIN Clientes c ON v.dni_cliente = c.dni
        JOIN Usuarios u ON c.dni = u.dni
        GROUP BY u.nombre, u.apellido_paterno
        ORDER BY gastado DESC
        FETCH FIRST 10 ROWS ONLY;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 8. TOP MEJORES CLIENTES ===');
    FOR r IN c_ventas_cli LOOP
        DBMS_OUTPUT.PUT_LINE(r.cliente || 
                             ' | Compras: ' || r.total_compras || 
                             ' | Gasto Total: S/.' || NVL(r.gastado, 0));
    END LOOP;
END;
/

-- ==========================================================
-- 9. REPORTE: TOP 5 MEDICAMENTOS MÁS VENDIDOS
-- ==========================================================
DECLARE
    CURSOR c_top IS
        SELECT m.nombre, SUM(d.cantidad) AS total_vendido
        FROM Venta_Detalle d
        JOIN Medicamentos m ON d.id_medicamento = m.id_medicamento
        GROUP BY m.nombre
        ORDER BY total_vendido DESC
        FETCH FIRST 5 ROWS ONLY;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 9. TOP 5 PRODUCTOS ESTRELLA ===');
    FOR r IN c_top LOOP
        DBMS_OUTPUT.PUT_LINE('#' || c_top%ROWCOUNT || ' ' || r.nombre || 
                             ' | Unidades vendidas: ' || r.total_vendido);
    END LOOP;
END;
/

-- ==========================================================
-- 10. REPORTE: INGRESOS POR MES (Finanzas)
-- ==========================================================
DECLARE
    CURSOR c_ingresos IS
        SELECT TO_CHAR(fecha_venta, 'YYYY-MM') AS mes,
               COUNT(id_venta) AS num_ventas,
               SUM(total_venta) AS total_mes
        FROM Ventas
        GROUP BY TO_CHAR(fecha_venta, 'YYYY-MM')
        ORDER BY mes DESC;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== 10. HISTORIAL DE INGRESOS MENSUALES ===');
    FOR r IN c_ingresos LOOP
        DBMS_OUTPUT.PUT_LINE('Mes: ' || r.mes || 
                             ' | Transacciones: ' || r.num_ventas || 
                             ' | Total Caja: S/.' || NVL(r.total_mes, 0));
    END LOOP;
END;
/